name: autofix.ci
on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
    push:
        branches:
            - master
permissions:
    contents: read

jobs:
    autofix:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v7
            - name: Set up pnpm
              uses: pnpm/action-setup@v6
            - name: Set up node and cache packages
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm
            - name: Install packages
              run: pnpm install --frozen-lockfile
            - name: Run prettier
              run: pnpm exec prettier . --write
            - name: Run eslint
              run: pnpm exec eslint --fix .
            - name: Commit changes
              uses: autofix-ci/action@v1
              with:
                  commit-message: Apply formatting changes
