name: Publish memory-viz package to npmjs

on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        environment:
            name: publish-npm
        steps:
            - uses: actions/checkout@v4
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v5
              with:
                  node-version: "24.x"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm publish --provenance --access public --workspace=memory-viz
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
