name: Publish memory-viz package to npmjs

on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        environment:
            name: publish-npm
        steps:
            - uses: actions/checkout@v7
            # Setup .npmrc file to publish to npm
            - name: Set up pnpm
              uses: pnpm/action-setup@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: "24.x"
                  registry-url: "https://registry.npmjs.org"
            - run: pnpm install --frozen-lockfile
            - run: pnpm --filter memory-viz publish --provenance --access public --no-git-checks
